sudo: required
language: bash
services:
  - docker
  - docker-compose

install:
  - git clone https://github.com/dminca/dockerized-drupal.git ~/repo

before_script:
  - cd ~/repo

script: make test -d