web:
  build: .
  ports:
    - "80:80"
  volumes:
    - ./app:/var/www/html
  links:
    - psql:db

psql:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=drupal
    - POSTGRES_USER=drupal
    - POSTGRES_DB=drupal
  # ports:
  #   - "5432:5432"
